import {
  SubstrateDatasourceKind,
  SubstrateEventHandler,
  SubstrateHandlerKind,
  SubstrateProject,
} from '@subql/types';

const startBlock = Number(process.env.START_BLOCK) || 1;
const chainId = process.env.NETWORK_CHAIN_ID || '';
const endpoint = process.env.NETWORK_ENDPOINT || '';
const dictionary = process.env.NETWORK_DICTIONARY || '';

const filters = {
  asset: {
    AssetAffirmationExemption: [],
    AssetBalanceUpdated: ['handleAssetBalanceUpdated'],
    AssetCreated: ['handleAssetCreated'],
    AssetFrozen: ['handleFrozen'],
    AssetMediatorsAdded: ['handleAssetMediatorsAdded'],
    AssetMediatorsRemoved: ['handleAssetMediatorsRemoved'],
    AssetOwnershipTransferred: ['handleAssetOwnershipTransferred'],
    AssetRenamed: ['handleAssetRenamed'],
    AssetTypeChanged: [],
    AssetUnfrozen: ['handleUnfrozen'],
    ControllerTransfer: [],
    CustomAssetTypeExists: [],
    CustomAssetTypeRegistered: [],
    DivisibilityChanged: ['handleDivisibilityChanged'],
    DocumentAdded: ['handleDocumentAdded'],
    DocumentRemoved: ['handleDocumentRemoved'],
    ExtensionRemoved: [],
    FundingRoundSet: ['handleFundingRoundSet'],
    GlobalMetadataSpecUpdated: [],
    IdentifiersUpdated: ['handleIdentifiersUpdated'],
    IsIssuable: [],
    Issued: ['handleIssued', 'handleAssetIssuedStatistics'],
    LocalMetadataKeyDeleted: [],
    MetadataValueDeleted: [],
    PreApprovedAsset: ['handlePreApprovedAsset'],
    RegisterAssetMetadataGlobalType: [],
    RegisterAssetMetadataLocalType: [],
    RemoveAssetAffirmationExemption: [],
    RemovePreApprovedAsset: ['handleRemovePreApprovedAsset'],
    Redeemed: ['handleRedeemed', 'handleAssetRedeemedStatistics'],
    SetAssetMetadataValue: [],
    SetAssetMetadataValueDetails: [],
    TickerLinkedToAsset: ['handleTickerLinkedToAsset'],
    TickerRegistered: ['handleTickerRegistered'],
    TickerTransferred: ['handleTickerTransferred'],
    TickerUnlinkedFromAsset: ['handleTickerUnlinkedFromAsset'],
    Transfer: ['handleAssetTransfer'],
    TransferWithData: [],
  },
  balances: {
    AccountBalanceBurned: ['handleBalanceBurned'],
    BalanceSet: ['handleBalanceSet'],
    Burned: ['handleBalanceBurned'],
    Deposit: ['handleBalanceDeposit'],
    DustLost: [],
    Endowed: ['handleBalanceEndowed'],
    Frozen: ['handleBalanceFrozen'],
    Issued: [],
    Locked: ['handleBalanceLocked'],
    Minted: ['handleBalanceMinted'],
    Rescinded: [],
    Reserved: ['handleBalanceReserved'],
    ReserveRepatriated: ['handleReserveRepatriated'],
    Restored: ['handleBalanceMinted'],
    Slashed: ['handleBalanceBurned'],
    Suspended: ['handleBalanceSuspended'],
    Thawed: [],
    TotalIssuanceForced: [],
    Transfer: ['handleBalanceTransfer'],
    TransferMemo: ['handleBalanceTransfer'],
    Unlocked: ['handleBalanceUnlocked'],
    Unreserved: ['handleBalanceUnreserved'],
    Upgraded: [],
    Withdraw: ['handleBalanceBurned'],
  },
  bridge: {
    AdminChanged: [],
    BridgeLimitUpdated: [],
    BridgeTxFailed: [],
    BridgeTxScheduleFailed: [],
    BridgeTxScheduled: [],
    Bridged: ['handleBridgeEvent'],
    ControllerChanged: [],
    ExemptedUpdated: [],
    FreezeAdminAdded: [],
    FreezeAdminRemoved: [],
    Frozen: [],
    FrozenTx: [],
    TimelockChanged: [],
    TxRemoved: [],
    TxsHandled: [],
    Unfrozen: [],
    UnfrozenTx: [],
  },
  capitalDistribution: {
    BenefitClaimed: ['handleBenefitClaimed'],
    Created: ['handleDistributionCreated'],
    Reclaimed: ['handleReclaimed'],
    Removed: ['handleDistributionRemoved'],
  },
  checkpoint: {
    CheckpointCreated: [],
    MaximumSchedulesComplexityChanged: [],
    ScheduleCreated: [],
    ScheduleRemoved: [],
  },
  complianceManager: {
    AssetCompliancePaused: ['handleAssetCompliancePaused'],
    AssetComplianceReplaced: ['handleComplianceReplaced'],
    AssetComplianceReset: ['handleComplianceReset'],
    AssetComplianceResumed: ['handleAssetComplianceResumed'],
    ComplianceRequirementChanged: [],
    ComplianceRequirementCreated: ['handleComplianceCreated'],
    ComplianceRequirementRemoved: ['handleComplianceRemoved'],
    TrustedDefaultClaimIssuerAdded: ['handleTrustedDefaultClaimIssuerAdded'],
    TrustedDefaultClaimIssuerRemoved: ['handleTrustedDefaultClaimIssuerRemoved'],
  },
  confidentialAsset: {
    AccountCreated: ['handleConfidentialAccountCreated'],
    AccountDeposit: ['handleConfidentialDepositOrWithdraw'],
    AccountDepositIncoming: ['handleAccountDepositIncoming'],
    AccountWithdraw: ['handleConfidentialDepositOrWithdraw'],
    AccountAssetFrozen: ['handleConfidentialAssetFrozenForAccount'],
    AccountAssetUnfrozen: ['handleConfidentialAssetUnfrozenForAccount'],
    AssetCreated: ['handleConfidentialAssetCreated'],
    AssetFrozen: ['handleAssetFrozenUnfrozen'],
    AssetUnfrozen: ['handleAssetFrozenUnfrozen'],
    AssetBurned: ['handleConfidentialAssetIssuedOrBurned'],
    Issued: ['handleConfidentialAssetIssuedOrBurned'],
    Burned: ['handleConfidentialAssetIssuedOrBurned'],
    TransactionAffirmed: ['handleConfidentialTransactionAffirmed'],
    TransactionCreated: ['handleConfidentialTransactionCreated'],
    TransactionExecuted: ['handleConfidentialTransactionExecutedOrRejected'],
    TransactionRejected: ['handleConfidentialTransactionExecutedOrRejected'],
    VenueCreated: ['handleConfidentialVenueCreated'],
    VenueFiltering: ['handleVenueFiltering'],
    VenuesAllowed: ['handleVenuesAllowed'],
    VenuesBlocked: ['handleVenuesBlocked'],
    FundsMoved: ['handleConfidentialAssetMoveFunds'],
  },
  corporateAction: {
    CAInitiated: [],
    CALinkedToDoc: [],
    CARemoved: [],
    DefaultTargetIdentitiesChanged: [],
    DefaultWithholdingTaxChanged: [],
    DidWithholdingTaxChanged: [],
    MaxDetailsLengthChanged: [],
    RecordDateChanged: [],
  },
  corporateBallot: {
    Created: [],
    MetaChanged: [],
    RangeChanged: [],
    RCVChanged: [],
    Removed: [],
    VoteCast: [],
  },
  externalAgents: {
    AgentAdded: ['handleExternalAgentAdded', 'handleAgentAdded'],
    AgentRemoved: ['handleExternalAgentRemoved', 'handleAgentRemoved'],
    GroupChanged: ['handleGroupChanged'],
    GroupCreated: ['handleGroupCreated'],
    GroupPermissionsUpdated: ['handleGroupPermissionsUpdated'],
  },
  identity: {
    AssetDidRegistered: ['handleDidRegistered'],
    AuthorizationAdded: ['handleAuthorization'],
    AuthorizationConsumed: ['handleAuthorization'],
    AuthorizationRejected: ['handleAuthorization'],
    AuthorizationRetryLimitReached: [],
    AuthorizationRevoked: ['handleAuthorization'],
    CddClaimsInvalidated: [],
    CddRequirementForPrimaryKeyUpdated: [],
    ChildDidCreated: ['handleChildDidCreated'],
    ChildDidUnlinked: ['handleChildDidUnlinked'],
    ClaimAdded: ['handleClaimAdded'],
    ClaimRevoked: ['handleClaimRevoked'],
    CustomClaimTypeAdded: ['handleCustomClaimTypeCreated'],
    DidCreated: ['handleDidCreated'],
    PrimaryKeyUpdated: ['handlePrimaryKeyUpdated'],
    SecondaryKeyLeftIdentity: ['handleSecondaryKeyLeftIdentity'],
    SecondaryKeyPermissionsUpdated: ['handleSecondaryKeysPermissionsUpdated'],
    SecondaryKeysAdded: ['handleSecondaryKeysAdded'],
    SecondaryKeysFrozen: ['handleSecondaryKeysFrozen'],
    SecondaryKeysRemoved: ['handleSecondaryKeysRemoved'],
    SecondaryKeysUnfrozen: ['handleSecondaryKeysUnfrozen'],
    SignerLeft: ['handleSignerLeft'],
  },
  multiSig: {
    MultiSigAddedAdmin: ['handleMultiSigAddedAdmin'],
    MultiSigCreated: ['handleMultiSigCreated'],
    MultiSigRemovedAdmin: ['handleMultiSigRemovedAdmin'],
    MultiSigRemovedPayingDid: [],
    MultiSigSignerAdded: ['handleMultiSigSignerAdded'],
    MultiSigSignerAuthorized: ['handleMultiSigSignerAuthorized'],
    MultiSigSignersAuthorized: ['handleMultiSigSignersAuthorized'],
    MultiSigSignerRemoved: ['handleMultiSigSignerRemoved'],
    MultiSigSignersRemoved: ['handleMultiSigSignersRemoved'],
    MultiSigSignaturesRequiredChanged: ['handleMultiSigSignaturesRequiredChanged'],
    MultiSigSignersRequiredChanged: ['handleMultiSigSignaturesRequiredChanged'],
    ProposalAdded: ['handleMultiSigProposalAdded'],
    ProposalApprovalVote: ['handleMultiSigVoteApproved'],
    ProposalApproved: ['handleMultiSigProposalApproved'],
    ProposalExecuted: ['handleMultiSigProposalExecuted'],
    ProposalExecutionFailed: [],
    ProposalRejected: ['handleMultiSigProposalRejected'],
    ProposalRejectionVote: ['handleMultiSigVoteRejected'],
    SchedulingFailed: [],
    ProposalFailedToExecute: [],
  },
  nft: {
    NFTPortfolioUpdated: ['handleNftPortfolioUpdates'],
    NftCollectionCreated: ['handleNftCollectionCreated'],
  },
  pips: {
    ActivePipLimitChanged: [],
    DefaultEnactmentPeriodChanged: [],
    ExecutionCancellingFailed: [],
    ExecutionScheduled: [],
    ExecutionSchedulingFailed: [],
    ExpiryScheduled: [],
    ExpirySchedulingFailed: [],
    HistoricalPipsPruned: [],
    MaxPipSkipCountChanged: [],
    MinimumProposalDepositChanged: [],
    PendingPipExpiryChanged: [],
    PipClosed: [],
    PipSkipped: [],
    ProposalCreated: ['handleProposalCreated'],
    ProposalRefund: [],
    ProposalStateUpdated: ['handleProposalStateUpdated'],
    SnapshotCleared: [],
    SnapshotResultsEnacted: [],
    SnapshotTaken: ['handleSnapshotTaken'],
    Voted: ['handleVoted'],
  },
  portfolio: {
    AllowIdentityToCreatePortfolios: [],
    FundsMovedBetweenPortfolios: ['handleFundsMovedBetweenPortfolios'],
    MovedBetweenPortfolios: ['handlePortfolioMovement'],
    PortfolioCreated: ['handlePortfolioCreated'],
    PortfolioCustodianChanged: ['handlePortfolioCustodianChanged'],
    PortfolioDeleted: ['handlePortfolioDeleted'],
    PortfolioRenamed: ['handlePortfolioRenamed'],
    PreApprovedPortfolio: [],
    RevokeCreatePortfoliosPermission: [],
    RevokePreApprovedPortfolio: [],
    UserPortfolios: [],
  },
  protocolFee: {
    FeeCharged: ['handleFeeCharged'],
  },
  settlement: {
    AffirmationWithdrawn: ['handleAffirmationWithdrawn'],
    FailedToExecuteInstruction: ['handleFailedToExecuteInstruction'],
    InstructionAffirmed: ['handleInstructionUpdate'],
    InstructionAutomaticallyAffirmed: ['handleAutomaticAffirmation'],
    InstructionAuthorized: ['handleInstructionUpdate'],
    InstructionCreated: ['handleInstructionCreated'],
    InstructionExecuted: ['handleInstructionFinalizedEvent'],
    InstructionFailed: ['handleInstructionFinalizedEvent'],
    InstructionLocked: ['handleInstructionFinalizedEvent'],
    InstructionMediators: ['handleInstructionMediators'],
    InstructionRejected: ['handleInstructionRejected'],
    InstructionRescheduled: [],
    InstructionUnauthorized: ['handleInstructionUpdate'],
    LegFailedExecution: [],
    MediatorAffirmationReceived: ['handleMediatorAffirmationReceived'],
    MediatorAffirmationWithdrawn: ['handleMediatorAffirmationWithdrawn'],
    ReceiptClaimed: ['handleReceiptClaimed'],
    SchedulingFailed: [],
    SettlementManuallyExecuted: ['handleSettlementManuallyExecuted'],
    VenueCreated: ['handleVenueCreated'],
    VenueDetailsUpdated: ['handleVenueDetailsUpdated'],
    VenueFiltering: [],
    VenuesAllowed: [],
    VenuesBlocked: [],
    VenueSignersUpdated: ['handleVenueSignersUpdated'],
    VenueTypeUpdated: ['handleVenueTypeUpdated'],
    VenueUnauthorized: [],
  },
  staking: {
    Bonded: ['handleStakingEvent', 'handleBonded'],
    Chilled: [],
    ControllerBatchDeprecated: [],
    CommissionCapUpdated: [],
    CurrencyMigrated: [],
    EraPaid: [],
    EraPayout: [],
    ForceEra: [],
    InvalidatedNominators: [],
    Kicked: [],
    MinimumBondThresholdUpdated: [],
    Nominated: ['handleStakingEvent'],
    OldSlashingReportDiscarded: [],
    PayoutStarted: [],
    PermissionedIdentityAdded: [],
    PermissionedIdentityRemoved: [],
    Reward: ['handleStakingEvent', 'handleReward'],
    Rewarded: ['handleStakingEvent', 'handleReward'],
    RewardPaymentSchedulingInterrupted: [],
    Slash: ['handleStakingEvent'],
    Slashed: ['handleStakingEvent'],
    SlashReported: [],
    SlashingAllowedForChanged: [],
    SnapshotTargetsSizeExceeded: [],
    SnapshotVotersSizeExceeded: [],
    SolutionStored: [],
    StakersElected: [],
    StakingElection: [],
    StakingElectionFailed: [],
    Unbonded: ['handleStakingEvent', 'handleUnbonded'],
    ValidatorPrefsSet: [],
    Withdrawn: ['handleWithdrawn'],
  },
  statistics: {
    AssetStatsUpdated: [],
    SetAssetTransferCompliance: ['handleSetTransferCompliance'],
    StatTypesAdded: ['handleStatTypeAdded'],
    StatTypesRemoved: ['handleStatTypeRemoved'],
    TransferManagerAdded: ['handleTransferManagerAdded', 'handleStatisticTransferManagerAdded'],
    TransferManagerRemoved: ['handleTransferManagerRemoved'],
    ExemptionsAdded: ['handleExemptionsAdded', 'handleTransferManagerExemptionsAdded'],
    ExemptionsRemoved: ['handleExemptionsRemoved', 'handleTransferManagerExemptionsRemoved'],
    TransferConditionExemptionsAdded: ['handleStatisticExemptionsAdded'],
    TransferConditionExemptionsRemoved: ['handleStatisticExemptionsRemoved'],
  },
  sto: {
    FundraiserClosed: ['handleStoClosed'],
    FundraiserCreated: ['handleFundraiserCreated'],
    FundraiserFrozen: ['handleStoFrozen'],
    FundraiserUnfrozen: ['handleStoUnfrozen'],
    FundraiserWindowModified: ['handleFundraiserWindowModified'],
    Invested: ['handleInvested'],
    FundraiserOffchainFundingEnabled: ['handleFundraiserOffchainFundingEnabled'],
  },
  system: {
    CodeUpdated: ['handleMigration'],
    NewAccount: [],
  },
  transactionPayment: {
    TransactionFeePaid: ['handleTransactionFeeCharged'],
  },
  treasury: {
    TreasuryDisbursement: ['handleTreasuryDisbursement'],
    TreasuryDisbursementFailed: [],
    TreasuryReimbursement: ['handleTreasuryReimbursement'],
  },
  validators: {
    CommissionCapUpdated: [],
    InvalidatedNominators: [],
    Nominated: ['handleStakingEvent'],
    PermissionedIdentityAdded: [],
    PermissionedIdentityRemoved: [],
    RewardPaymentSchedulingInterrupted: [],
    SlashingAllowedForChanged: [],
  },
};

const handlers: SubstrateEventHandler[] = [];
const eventSpecificHandlers: SubstrateEventHandler[] = [];

Object.keys(filters).forEach(module => {
  if (module !== 'system') {
    handlers.push({
      kind: SubstrateHandlerKind.Event,
      handler: 'handleEvent',
      filter: {
        module,
      },
    } as SubstrateEventHandler);
  }

  Object.keys(filters[module]).forEach(method => {
    if (module === 'system') {
      handlers.push({
        kind: SubstrateHandlerKind.Event,
        handler: 'handleEvent',
        filter: {
          module,
          method,
        },
      } as SubstrateEventHandler);
    }

    if (filters[module][method].length > 0) {
      const handlerList = filters[module][method];

      handlerList.forEach(handler => {
        eventSpecificHandlers.push({
          kind: SubstrateHandlerKind.Event,
          handler,
          filter: {
            module,
            method,
          },
        } as SubstrateEventHandler);
      });
    }
  });
});

const project: SubstrateProject = {
  specVersion: '1.0.0',
  version: '0.0.1',
  name: 'polkadot-starter',
  description: 'This project can be used as a starting point for developing your SubQuery project',
  runner: {
    node: {
      name: '@subql/node',
      version: '>=3.0.1',
    },
    query: {
      name: '@subql/query',
      version: '*',
    },
  },
  schema: {
    file: './schema.graphql',
  },
  network: {
    /* The genesis hash of the network (hash of block 0) */
    chainId,
    /**
     * This endpoint must be a public non-pruned archive node
     * Public nodes may be rate limited, which can affect indexing speed
     * When developing your project we suggest getting a private API key
     * You can get them from OnFinality for free https://app.onfinality.io
     * https://documentation.onfinality.io/support/the-enhanced-api-service
     */
    endpoint: [endpoint],
    dictionary,
    chaintypes: {
      file: './dist/chainTypes.js',
    },
  },
  dataSources: [
    {
      kind: SubstrateDatasourceKind.Runtime,
      startBlock: 1,
      endBlock: 1,
      mapping: {
        file: './dist/index.js',
        handlers: [
          {
            kind: SubstrateHandlerKind.Block,
            handler: 'handleGenesis',
          },
        ],
      },
    },
    {
      kind: SubstrateDatasourceKind.Runtime,
      startBlock,
      mapping: {
        file: './dist/index.js',
        handlers: eventSpecificHandlers,
      },
    },
    {
      kind: SubstrateDatasourceKind.Runtime,
      startBlock,
      mapping: {
        file: './dist/index.js',
        handlers,
      },
    },
  ],
};

// Must set default to the project instance
export default project;
