/**
 * The metadata contract: every registered decoder must agree with the chain's own metadata about
 * how many parameters an event carries.
 *
 * This is what mechanically detects "the chain changed a shape and we did not notice". It needs
 * no chain and no database - the arity of every event, per spec version, is checked in under
 * `tests/fixtures/event-arity`, regenerated by `scripts/sync-metadata.ts`.
 */
import { readdirSync, readFileSync } from 'fs';
import { join } from 'path';
import { acceptedArity, EventShape, registeredShapes } from '../../src/decode';

const FIXTURE_DIR = join(__dirname, '..', 'fixtures', 'event-arity');

interface ArityFixture {
  specVersion: number;
  source: string;
  modules: Record<string, Record<string, number>>;
  /** Per module, the events that name their fields and so decode without a registered shape */
  named?: Record<string, string[]>;
}

const fixtures: ArityFixture[] = readdirSync(FIXTURE_DIR)
  .filter(name => name.endsWith('.json'))
  .map(name => JSON.parse(readFileSync(join(FIXTURE_DIR, name), 'utf-8')));

const covering = (shapes: readonly EventShape[], specVersion: number): EventShape[] =>
  shapes.filter(({ from, to }) => specVersion >= from && (to === undefined || specVersion <= to));

/** `moduleId.eventId` as the registry keys it */
const key = (moduleId: string, eventId: string) => `${moduleId.toLowerCase()}.${eventId}`;

describe('registered decoders against checked-in metadata', () => {
  it('has at least one spec version to check', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  describe.each(fixtures.map(fixture => [fixture.specVersion, fixture] as const))(
    'spec version %s',
    (specVersion, fixture) => {
      const shapes = registeredShapes();

      const declared = Object.entries(fixture.modules).flatMap(([moduleId, events]) =>
        Object.entries(events).map(([eventId, arity]) => ({ moduleId, eventId, arity }))
      );

      it('accepts the parameter count the metadata declares for every covered event', () => {
        const disagreements = declared
          .map(({ moduleId, eventId, arity }) => {
            const applicable = covering(shapes.get(key(moduleId, eventId)) ?? [], specVersion);

            if (applicable.length === 0) {
              return undefined;
            }

            const accepted = applicable.some(shape => {
              const { min, max } = acceptedArity(shape);

              return arity >= min && arity <= max;
            });

            return accepted
              ? undefined
              : `${moduleId}.${eventId}: metadata says ${arity}, decoders accept ${applicable
                  .map(shape => {
                    const { min, max } = acceptedArity(shape);

                    return min === max ? `${max}` : `${min}-${max}`;
                  })
                  .join(' or ')}`;
          })
          .filter(Boolean);

        expect(disagreements).toEqual([]);
      });

      /**
       * The failure that stops a block: an event the chain emits, that some handler decodes, with no
       * shape covering this runtime. Named-field events are exempt — they decode from the block's
       * own metadata and the table is never consulted for them.
       *
       * The opposite direction — a decoder covering a runtime where its event does not exist — is
       * deliberately not an error. It is never invoked for the wrong era, and the node labels blocks
       * near an upgrade with the neighbouring runtime's spec, so a range that stops exactly at the
       * event's introduction would leave those blocks with no decoder at all.
       */
      it('has a decoder for every tuple-style event this runtime emits', () => {
        const uncovered = declared
          .filter(({ moduleId, eventId }) => !fixture.named?.[moduleId]?.includes(eventId))
          .filter(({ moduleId, eventId }) => {
            const registered = shapes.get(key(moduleId, eventId));

            return registered !== undefined && covering(registered, specVersion).length === 0;
          })
          .map(({ moduleId, eventId }) => `${moduleId}.${eventId}`);

        expect(uncovered).toEqual([]);
      });
    }
  );

  /** A decoder whose event no checked-in runtime has is a misspelling or a stale entry. */
  it('registers decoders only for events some checked-in runtime has', () => {
    const known = new Set(
      fixtures.flatMap(fixture =>
        Object.entries(fixture.modules).flatMap(([moduleId, events]) =>
          Object.keys(events).map(eventId => key(moduleId, eventId))
        )
      )
    );
    const capturedModules = new Set(
      fixtures.flatMap(fixture =>
        Object.keys(fixture.modules).map(moduleId => moduleId.toLowerCase())
      )
    );

    const unknown = [...registeredShapes().keys()]
      .filter(shapeKey => capturedModules.has(shapeKey.split('.')[0]))
      .filter(shapeKey => !known.has(shapeKey));

    expect(unknown).toEqual([]);
  });
});
