/**
 * The metadata contract: every registered decoder must agree with the chain's own metadata about
 * how many parameters an event carries.
 *
 * This is what mechanically detects "the chain changed a shape and we did not notice". It needs
 * no chain and no database - the arity of every event, per spec version, is checked in under
 * `tests/fixtures/event-arity`, regenerated by `scripts/sync-metadata.ts`.
 */
import { readdirSync, readFileSync } from 'fs';
import { join } from 'path';
import { acceptedArity, EventShape, registeredShapes } from '../../src/decode';

const FIXTURE_DIR = join(__dirname, '..', 'fixtures', 'event-arity');

interface ArityFixture {
  specVersion: number;
  source: string;
  modules: Record<string, Record<string, number>>;
}

const fixtures: ArityFixture[] = readdirSync(FIXTURE_DIR)
  .filter(name => name.endsWith('.json'))
  .map(name => JSON.parse(readFileSync(join(FIXTURE_DIR, name), 'utf-8')));

const covering = (shapes: readonly EventShape[], specVersion: number): EventShape[] =>
  shapes.filter(({ from, to }) => specVersion >= from && (to === undefined || specVersion <= to));

/** `moduleId.eventId` as the registry keys it */
const key = (moduleId: string, eventId: string) => `${moduleId.toLowerCase()}.${eventId}`;

describe('registered decoders against checked-in metadata', () => {
  it('has at least one spec version to check', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  describe.each(fixtures.map(fixture => [fixture.specVersion, fixture] as const))(
    'spec version %s',
    (specVersion, fixture) => {
      const shapes = registeredShapes();

      const declared = Object.entries(fixture.modules).flatMap(([moduleId, events]) =>
        Object.entries(events).map(([eventId, arity]) => ({ moduleId, eventId, arity }))
      );

      it('accepts the parameter count the metadata declares for every covered event', () => {
        const disagreements = declared
          .map(({ moduleId, eventId, arity }) => {
            const applicable = covering(shapes.get(key(moduleId, eventId)) ?? [], specVersion);

            if (applicable.length === 0) {
              return undefined;
            }

            const accepted = applicable.some(shape => {
              const { min, max } = acceptedArity(shape);

              return arity >= min && arity <= max;
            });

            return accepted
              ? undefined
              : `${moduleId}.${eventId}: metadata says ${arity}, decoders accept ${applicable
                  .map(shape => {
                    const { min, max } = acceptedArity(shape);

                    return min === max ? `${max}` : `${min}-${max}`;
                  })
                  .join(' or ')}`;
          })
          .filter(Boolean);

        expect(disagreements).toEqual([]);
      });

      it('registers no decoder for an event this runtime does not have', () => {
        const covered = new Set(
          declared
            .filter(({ moduleId }) => fixture.modules[moduleId])
            .map(({ moduleId, eventId }) => key(moduleId, eventId))
        );
        const fixtureModules = Object.keys(fixture.modules).map(moduleId => moduleId.toLowerCase());

        const orphans = [...shapes.entries()]
          .filter(([shapeKey]) => fixtureModules.includes(shapeKey.split('.')[0]))
          .filter(([, entries]) => covering(entries, specVersion).length > 0)
          .map(([shapeKey]) => shapeKey)
          .filter(shapeKey => !covered.has(shapeKey));

        expect(orphans).toEqual([]);
      });
    }
  );
});
