/**
 * Assets issued before v5.0 had an implicitly made Count statistics
 *
 * This is a list for testnet and mainnet obtained with:
 *
 * ```sh
 * curl 'http://localhost:3007/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3007' --data-binary '{"query":"query issued {\n  events(filter: {blockId: {lessThan: \"4397818\"},eventId: {equalTo: Issued}}) {\n    nodes{\n      id\n      eventArg0\n      eventArg1\n      eventArg2\n      eventArg3\n    }\n  }\n}\n"}' --compressed | jq '.data.events.nodes | map(.eventArg1) | unique' | tee /tmp/asset_list.txt
 * ```
 */

export const legacyAssets = {
  'Polymesh Mainnet': [
    '20220824',
    'ABC',
    'CUBEY',
    'PAC10',
    'TEST-TOKEN-1',
    'THC',
    'TKSETEST10',
    'USPC',
  ],
  'Polymesh Testnet': [
    '20211219',
    '20211220',
    'ABCD',
    'ABCF',
    'ADAMTEST1',
    'ALAW',
    'ALAWSC',
    'BETS',
    'BITS',
    'BRAINZ',
    'CAKES',
    'CATALYSTTEST',
    'COOKIES',
    'CSBT',
    'CSBT2',
    'CTEST1',
    'CXVY',
    'DEEPUSD2',
    'DRONZ',
    'EFRER',
    'FFFF',
    'FLASH',
    'GARRETTDEBT',
    'GILT',
    'GOLDFISH',
    'GTEST1',
    'KASKASH',
    'KBBL',
    'KIRI',
    'MAGOO',
    'MAIN',
    'MAINDIV',
    'MODS',
    'NADATING',
    'NEO',
    'NEWX',
    'NOUIDNEEDED',
    'NUNIQ',
    'NUNIQ2',
    'NUNU',
    'QQ',
    'REAPP',
    'REBELKING007',
    'ROBERT1',
    'RTTL',
    'SCOIN',
    'SDC',
    'SDCSDC',
    'SEED',
    'SLAY',
    'SNAKEYES',
    'ST1',
    'STOZO',
    'SYMB',
    'TEST        ',
    'TEST5',
    'TESTSEC',
    'TESTSEC1',
    'TMAE',
    'TRIUMPH',
    'TRUMBLE',
    'UID',
    'UID-REQUIRED',
    'UNUNIQUE',
    'W-POLYX',
    'WEWEWE',
    'WING',
    'WWW',
    'XTREME',
    'YOLO',
  ],
};
